name: deploy

on:
  push:
    branches:
      -main

jobs: 
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-18.04
    steps:
      - name: build and push to docker
        run: |
          echo "Hola Mundo"
